### ISSUE TITLE
Stuck creating a new project

### ISSUE THREAD

**Issue by gmwishwas** [hipster-labs/generator-jhipster-react#10]
@deepu105  - I tried to create a project and got stuck on `Would you like to enable this option? (Y/n)` and Y or n doesnt make any difference since there are no package.json or bower json file. Is this still being worked on? I saw that there have been no commits the last 3 months. Just wanted to check.

I tried to download the code and run the generator locally. But there seems to be some issue with the Jhipster generator. If I use 2.27.x, I get an error 

Composing JHipster configuration with module react
TypeError: Cannot read property 'endsWith' of undefined
    at Generator.getAngularAppName (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base.js:1229:61)
    at new module.exports.ModulesGenerator.extend.constructor (/usr/local/lib/node_modules/generator-jhipster/generators/modules/index.js:58:46)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:328:10)

If I use, 3.1.x, It says Cannot find module 'generator-jhipster'.

Thanks in advance !

**Comment by deepu105** [comment]
Yes its still being worked on. Currently the generated project has full
backend and only a react build and a index page, there is no security
integration or other modules like jhipster angular. I dont have enough time
and hence would appreciate any help to move the project forward.

For the issue you mentioned, it should atleast create a basic project ill
take a look

**Comment by jlehmer** [comment]
Since this is still an issue I've been digging in to see if this is something I can fix. I can see that the `this.composeWith('jhipster:modules', {
        options: {
          jhipsterVar: jhipsterVar,
          jhipsterFunc: jhipsterFunc,
          skipValidation: true
        }
      });`

is what's no longer working. The implicit requirement in jhipster:modules is that there exists a non-null "baseName" in the .yo-rc.json file. Since this file doesn't exist yet for the project it causes the generation to error out.

@deepu105 should we first create an issue in generator-jhipster project to address this first or is there a way to override the baseName value in the "this.config" property?

**Comment by deepu105** [comment]
I would like to get that fixed here rather than in the generator by may be creating a compatible yo-rc file
