### ISSUE TITLE
Error running jhipster-react with PT-BR translation

### ISSUE THREAD

**Issue by carlos-max** [hipster-labs/generator-jhipster-react#21]
If I enable the PT-BR(Brazilian Portuguese) translation on a jhipster-react project, the error below is shown:

![image](https://user-images.githubusercontent.com/16707756/27561038-eb9054ea-5a9c-11e7-9636-42c8c4e632d6.png)

If I remove the "-" symbol, I can successfuly run the app, but the translation won't work.

**Comment by deepu105** [comment]
Please note that this generator is a work in progress, so I cannot
guarantee success across all scenarios.

On 26 Jun 2017 11:27 pm, "carlos-max" <notifications@github.com> wrote:

If I enable the PT-BR(Brazilian Portuguese) translation on a jhipster-react
project, the error below is shown:

[image: image]
<https://user-images.githubusercontent.com/16707756/27561038-eb9054ea-5a9c-11e7-9636-42c8c4e632d6.png>

If I remove the "-" symbol, I can successfuly run the app, but the
translation won't work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hipster-labs/generator-jhipster-react/issues/21>, or mute
the thread

**Comment by carlos-max** [comment]
Sure @deepu105, great work so far.

I was just trying to collaborate by backlogging this issue

It seems that React doesn't accept the 'pt-br' constant, changing to' pt_br' solved the issue.
There's a chance this error might occur in other languages like pt-pt, so changing all language constants from '-' to '_' may solve future problems.

**Comment by deepu105** [comment]
Thanks ill look into that

**Comment by deepu105** [comment]
This is a WIP and the repo is deprecated as the project is moved into the main jhipster generator. Please look at the readme
